/**
 * vnmaker 시나리오 스키마 — 이 파일이 전체 파이프라인의 계약이다.
 * 시나리오 작성 노드, 플레이어 엔진, e2e 테스트가 모두 이 타입을 기준으로 동작한다.
 * 스키마를 바꾸면 세 곳이 같이 깨진다. 필드 추가는 optional 로만 한다.
 *
 * 열린 캐스트: CharacterId / Expression 은 닫힌 union 이 아니라 slug 문자열이다.
 * 주인공도 별도 매직 토큰이 아니라 characters 의 평범한 한 항목(관례상 id "me")이다.
 * 실제 slug 규칙(^[a-z0-9-]+$)은 content 체커(findManifestViolations)가 강제한다.
 */

/** 등장인물 id. 어떤 slug 든 올 수 있다. 브랜드로 일반 텍스트와 구분한다. */
export type CharacterId = string & { readonly __characterId?: "CharacterId" };

/** 표정. 스프라이트 파일명 규칙: sprite/<characterId>-<expression>.png */
export type Expression = string;

/** 등장인물 슬롯. left/center/right + offstage 를 기본으로, 필요하면 확장 가능하다. */
export type SpriteSlot = "left" | "center" | "right" | "offstage" | (string & {});

/** 화면 전환 효과. */
export type Transition = "none" | "fade" | "dissolve" | "flash" | "fadeToBlack";

/** 배우 배치 지시. character 가 null 이면 슬롯을 비운다. */
export interface SpriteDirection {
  readonly slot: SpriteSlot;
  readonly character: CharacterId | null;
  readonly expression?: Expression;
  /** A different pose; null returns this actor to the expression artwork. */
  readonly poseUrl?: string | null;
}

export type StoryFlags = Readonly<Record<string, string | number | boolean>>;
export interface FlagComparison { readonly flag: string; readonly op: "eq" | "ne" | "gt" | "gte" | "lt" | "lte"; readonly value: string | number | boolean }
export interface LineCondition { readonly all?: readonly string[]; readonly none?: readonly string[]; readonly compare?: readonly FlagComparison[] }

/** 대사 한 줄. speaker 가 null 이면 내레이션. 주인공도 일반 CharacterId 다. */
export interface Line {
  /** Stable identity within this scene; legacy manuscripts may omit it. */
  readonly id?: string;
  readonly speaker: CharacterId | null;
  readonly text: string;
  /** 이 줄에서 표정만 바꿀 때 사용. */
  readonly expression?: Expression;
  /** 이 줄과 함께 재생할 효과음 id. */
  readonly sfx?: string;
  /** Voice recording for this line; playback stops when advancing. */
  readonly voice?: string;
  /** 이 줄에서 화면을 흔든다. */
  readonly shake?: boolean;
  /** 이 줄에서 CG 를 숨긴다. */
  readonly cgHide?: boolean;
  /** Omit to keep the current image; null returns to the scene background. */
  readonly cgUrl?: string | null;
  /** Switch the underlying scene background at this line; omission keeps the latest cue. */
  readonly backgroundUrl?: string;
  readonly when?: LineCondition;
  /** Patch the listed actor slots without changing other actors. */
  readonly sprites?: readonly SpriteDirection[];
  readonly framing?: "wide" | "close" | "cinematic";
  readonly bgm?: string | null;
}

export interface Choice {
  /** Stable identity within this scene, separate from line IDs. */
  readonly id?: string;
  readonly text: string;
  /** 이동할 scene id. */
  readonly next: string;
  /** 이 선택으로 올라가는 호감도 플래그. */
  readonly affection?: number;
  /** 이 선택지가 보일 조건 플래그식. */
  readonly cond?: string;
  /** All requirements must pass for this choice to be shown. */
  readonly when?: LineCondition;
  /** 이 선택을 고르면 세팅할 플래그들. */
  readonly set?: Record<string, string | number | boolean>;
  /** Signed numeric changes applied to existing numeric flags. Keys cannot also appear in set. */
  readonly add?: Record<string, number>;
  /** true 면 선택 불가 상태로 표시한다. */
  readonly disable?: boolean;
}

export interface Scene {
  readonly id: string;
  /** 화면 좌상단에 표시할 장 제목. 없으면 표시하지 않는다. */
  readonly chapter?: string;
  readonly background: string;
  /** Optional artwork generated by the local image gateway. */
  readonly backgroundUrl?: string;
  /** A full-frame event illustration overrides the background while this scene plays. */
  readonly cgUrl?: string;
  readonly hideSprites?: boolean;
  readonly framing?: "wide" | "close" | "cinematic";
  readonly artBrief?: string;
  readonly bgm?: string;
  /** 이 씬에서 전체화면으로 표시할 CG id. */
  readonly cg?: string;
  readonly transition?: Transition;
  readonly sprites?: readonly SpriteDirection[];
  readonly lines: readonly Line[];
  /** 선택지가 있으면 next 는 무시된다. */
  readonly choices?: readonly Choice[];
  readonly next?: string;
  /** 엔딩 씬이면 엔딩 제목. 이 값이 있으면 엔딩 화면으로 넘어간다. */
  readonly ending?: string;
}

export interface Character {
  readonly id: CharacterId;
  readonly name: string;
  readonly color: string;
  readonly bio: string;
  /** 갈아입힐 수 있는 의상 id 목록. */
  readonly outfits?: string[];
  readonly expressionImages?: Partial<Readonly<Record<Expression, string>>>;
  /** Runtime keyed-image compositing; source art remains an unmodified bitmap. */
  readonly chromaKey?: "#00ff00";
}

export interface VnScript {
  /** Stable native release/save namespace; keep it when updating the same game. */
  readonly nativeSaveId?: string;
  readonly title: string;
  readonly subtitle: string;
  /** Ordered public team credits. Empty draft fields are allowed while authoring. */
  readonly credits?: readonly { readonly role: string; readonly names: string }[];
  readonly start: string;
  readonly characters: readonly Character[];
  readonly scenes: readonly Scene[];
  /** 전역 플래그 초기값. */
  readonly flags?: Record<string, string | number | boolean>;
  readonly artDirection?: string;
  /** Project-wide music start/change/stop fade duration; seconds, 0..10. */
  readonly musicFadeSeconds?: number;
  readonly assets?: readonly Artwork[];
  readonly audioAssets?: readonly AudioAsset[];
  readonly assetLibraryMode?: "project" | "all";
}

export interface AudioAsset {
  readonly provenance?: MediaProvenance;
  readonly id: string;
  readonly name: string;
  readonly kind: "bgm" | "sfx" | "voice";
  readonly url: string;
  readonly duration: number;
}

/** Reusable artwork owned by the project. URLs are served locally. */
export interface Artwork {
  /** Per-image policy; omission retains the legacy character chroma-key behavior. */
  readonly compositing?: "alpha" | "legacy-chroma-key" | "opaque";
  readonly provenance?: MediaProvenance;
  readonly id: string;
  readonly name: string;
  readonly kind: "background" | "cg" | "character";
  readonly url: string;
  readonly prompt?: string;
  readonly sceneId?: string;
  readonly characterId?: CharacterId;
  readonly expression?: Expression;
  readonly createdAt?: string;
}

/** Author-supplied records; presence does not establish redistribution rights. */
export interface MediaProvenance {
  readonly creator?: string;
  readonly source?: string;
  readonly license?: string;
  readonly credit?: string;
}
