import { BACKGROUNDS, BGM, EXPRESSIONS, SFX } from "@vnmaker/content";
import type { Expression, Line, Scene, SpriteDirection, VnScript } from "@vnmaker/content";
import { Icon } from "./Icon.js";
import { sceneTitle } from "./project.js";
import { speakerName } from "../engine/selectors.js";

export const expressionLabel = (expression: string) => ({ neutral: "기본", smile: "미소", sad: "슬픔", surprised: "놀람" })[expression] ?? "유지";
interface Props { script: VnScript; scene: Scene; lineIndex: number; patchScene: (scene: Scene, group?: string) => void; patchLine: (line: Line) => void }
export function Inspector({ script, scene, lineIndex, patchScene, patchLine }: Props) {
  const line = scene.lines[lineIndex]!;
  function exit(value: string) {
    const { choices: _choices, next: _next, ending: _ending, ...rest } = scene;
    patchScene({ ...rest, ...(value === "ending" ? { ending: scene.chapter || "이야기의 끝" } : { next: value }) });
  }
  return <div className="inspector-content">
    <div className="section-kicker">DIALOGUE <span>{String(lineIndex + 1).padStart(2, "0")}</span></div>
    <label className="studio-field">대사<textarea data-testid="studio-line-text" value={line.text} rows={5} onChange={event => patchLine({ ...line, text: event.target.value })} /></label>
    <div className="field-pair"><label className="studio-field">화자<select aria-label="화자" value={line.speaker ?? ""} onChange={event => patchLine({ ...line, speaker: (event.target.value || null) as Line["speaker"] })}><option value="">내레이션</option><option value="me">정우진</option>{script.characters.map(character => <option key={character.id} value={character.id}>{character.name}</option>)}</select></label><label className="studio-field">표정<select aria-label="표정" value={line.expression ?? ""} onChange={event => { const { expression: _expression, ...rest } = line; patchLine(event.target.value ? { ...rest, expression: event.target.value as Expression } : rest); }}><option value="">유지</option>{EXPRESSIONS.map(value => <option key={value} value={value}>{expressionLabel(value)}</option>)}</select></label></div>
    <label className="studio-field">효과음<select value={line.sfx ?? ""} onChange={event => { const { sfx: _sfx, ...rest } = line; patchLine(event.target.value ? { ...rest, sfx: event.target.value } : rest); }}><option value="">없음</option>{Object.entries(SFX).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    <label className="check-field"><input type="checkbox" checked={line.shake ?? false} onChange={event => patchLine({ ...line, shake: event.target.checked })} />화면 흔들림</label>
    <label className="studio-field" style={{ marginTop: 18 }}>이 대사에서 배경 전환<select aria-label="이 대사에서 배경 전환" data-testid="studio-line-background" value={line.backgroundUrl ?? ""} onChange={event => { const { backgroundUrl: _background, ...rest } = line; patchLine(event.target.value ? { ...rest, backgroundUrl: event.target.value } : rest); }}><option value="">이전 배경 유지</option>{line.backgroundUrl && !script.assets?.some(asset => asset.kind === "background" && asset.url === line.backgroundUrl) && <option value={line.backgroundUrl}>현재 지정된 배경</option>}{script.assets?.filter(asset => asset.kind === "background").map(asset => <option value={asset.url} key={asset.id}>{asset.name}</option>)}</select></label>
    <label className="studio-field" style={{ marginTop: 18 }}>이 대사에서 이미지 전환<select aria-label="대사 CG 연출" value={line.cgUrl === null ? "clear" : line.cgUrl ?? "inherit"} onChange={event => { const { cgUrl: _cue, ...rest } = line; patchLine(event.target.value === "inherit" ? rest : { ...rest, cgUrl: event.target.value === "clear" ? null : event.target.value }); }}><option value="inherit">이전 이미지 유지</option><option value="clear">장면 배경으로 돌아오기</option>{script.assets?.filter(asset => asset.kind === "cg").map(asset => <option value={asset.url} key={asset.id}>CG · {asset.name}</option>)}</select></label>
    <div className="section-kicker">SCENE <Icon name="scenes" size={14} /></div>
    <label className="studio-field">씬 이름<input value={scene.chapter ?? ""} onChange={event => patchScene({ ...scene, chapter: event.target.value }, `chapter-${scene.id}`)} /></label>
    <label className="studio-field">배경<select aria-label="장면 배경" value={scene.backgroundUrl ?? scene.background} onChange={event => { const { backgroundUrl: _url, cgUrl: _cg, ...rest } = scene; patchScene(event.target.value.startsWith("/") ? { ...rest, backgroundUrl: event.target.value } : { ...rest, background: event.target.value }); }}>{scene.backgroundUrl && !script.assets?.some(asset => asset.url === scene.backgroundUrl) && <option value={scene.backgroundUrl}>프로젝트 배경</option>}{script.assets?.filter(asset => asset.kind === "background").map(asset => <option key={asset.id} value={asset.url}>{asset.name}</option>)}<optgroup label="기본 배경">{Object.entries(BACKGROUNDS).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</optgroup></select></label>
    <label className="studio-field">배경음악<select value={scene.bgm ?? ""} onChange={event => { const { bgm: _bgm, ...rest } = scene; patchScene(event.target.value ? { ...rest, bgm: event.target.value } : rest); }}><option value="">없음</option>{Object.entries(BGM).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    <label className="studio-field">장면 전환<select value={scene.transition ?? "none"} onChange={event => patchScene({ ...scene, transition: event.target.value as Scene["transition"] & string })}>{[["none", "없음"], ["fade", "페이드"], ["dissolve", "디졸브"], ["flash", "플래시"], ["fadeToBlack", "암전"]].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    <div className="section-kicker">ART & CAMERA <Icon name="image" size={14} /></div>
    {scene.cgUrl && <div className="inspector-cg"><img src={scene.cgUrl} alt="현재 장면의 이벤트 CG" /><div><span>이벤트 CG 적용 중</span><button type="button" className="text-button" onClick={() => { const { cgUrl: _cg, ...rest } = scene; patchScene(rest); }}>CG 해제</button></div></div>}
    <label className="studio-field">카메라 프레이밍<select aria-label="카메라 프레이밍" value={scene.framing ?? "wide"} onChange={event => patchScene({ ...scene, framing: event.target.value as NonNullable<Scene["framing"]> })}><option value="wide">와이드 · 전체 장면</option><option value="close">클로즈업 · 감정 강조</option><option value="cinematic">시네마틱 · 레터박스</option></select></label>
    <label className="check-field"><input type="checkbox" checked={scene.hideSprites ?? false} onChange={event => patchScene({ ...scene, hideSprites: event.target.checked })} />배우 없이 배경만 보여주기</label>
    <p className="field-help" style={{ marginTop: 10 }}>이벤트 CG가 있으면 배우 이미지 대신 CG를 표시합니다.</p>
    <label className="studio-field">장면 아트 브리프<textarea aria-label="장면 연출 메모" value={scene.artBrief ?? ""} rows={3} maxLength={4000} placeholder="시간대, 빛, 소품, 감정의 시각적 모티프…" onChange={event => patchScene({ ...scene, artBrief: event.target.value }, `art-${scene.id}`)} /></label>
    <div className="section-kicker">CAST <Icon name="users" size={14} /></div>
    {(["left", "center", "right"] as const).map(slot => <label className="studio-field" key={slot}>{slot === "left" ? "왼쪽" : slot === "center" ? "중앙" : "오른쪽"}<select aria-label={`${slot} 배우`} value={scene.sprites?.find(sprite => sprite.slot === slot)?.character ?? ""} onChange={event => { const sprites = (scene.sprites ?? []).filter(sprite => sprite.slot !== slot); const character = event.target.value as SpriteDirection["character"]; patchScene({ ...scene, sprites: character ? [...sprites, { slot, character, expression: "neutral" }] : sprites }); }}><option value="">비우기</option>{script.characters.map(character => <option key={character.id} value={character.id}>{speakerName(script, character.id)}</option>)}</select></label>)}
    <div className="section-kicker">STORY FLOW <Icon name="graph" size={14} /></div>
    {scene.choices?.length ? <div className="choice-fields">{scene.choices.map((choice, index) => <div className="choice-edit" key={index}><div className="choice-edit-heading"><span>선택지 {index + 1}</span><button type="button" className="icon-button" aria-label={`선택지 ${index + 1} 삭제`} onClick={() => { const choices = scene.choices!.filter((_, i) => i !== index); if (choices.length) patchScene({ ...scene, choices }); else exit("ending"); }}><Icon name="close" size={13} /></button></div><input aria-label={`선택지 ${index + 1} 문구`} value={choice.text} onChange={event => patchScene({ ...scene, choices: scene.choices!.map((row, i) => i === index ? { ...row, text: event.target.value } : row) }, `choice-${scene.id}-${index}`)} /><select aria-label={`선택지 ${index + 1} 연결`} value={choice.next} onChange={event => patchScene({ ...scene, choices: scene.choices!.map((row, i) => i === index ? { ...row, next: event.target.value } : row) })}>{script.scenes.map(row => <option key={row.id} value={row.id}>{sceneTitle(row)}</option>)}</select></div>)}</div> : <label className="studio-field">이 씬이 끝나면<select aria-label="씬 종료 방식" value={scene.ending ? "ending" : scene.next ?? ""} onChange={event => exit(event.target.value)}><option value="" disabled>연결할 씬 선택</option><option value="ending">엔딩 표시</option>{script.scenes.map(row => <option key={row.id} value={row.id}>{sceneTitle(row)}</option>)}</select></label>}
    {scene.ending && !scene.choices?.length && <label className="studio-field">엔딩 제목<input value={scene.ending} onChange={event => patchScene({ ...scene, ending: event.target.value }, `ending-${scene.id}`)} /></label>}
    <button className="studio-button full-width" type="button" disabled={(scene.choices?.length ?? 0) >= 8} onClick={() => { const { ending: _ending, next: _next, ...rest } = scene; const target = scene.next ?? script.scenes.find(row => row.id !== scene.id)?.id ?? scene.id; patchScene({ ...rest, choices: [...(scene.choices ?? []), { text: "새로운 선택", next: target }] }); }}><Icon name="plus" />선택지 추가</button>
  </div>;
}
