import {AudioLibrary,AudioOptions} from "./AudioLibrary.js";
import { StateEditor, ConditionEditor, ChoiceStateEditor } from "./StateEditor.js";
import { BACKGROUNDS, BGM, LIMITS, SFX, characterExpressions } from "@vnmaker/content";
import type { Expression, Line, Scene, SpriteDirection, VnScript } from "@vnmaker/content";
import { memo, useEffect, useMemo, useState, type RefObject } from "react";
import { Icon } from "./Icon.js";
import { sceneTitle } from "./project.js";
import { splitPastedText, stripSpeakerPrefix } from "./lineOperations.js";
import { speakerName, spritesAt } from "../engine/selectors.js";

export const expressionLabel = (expression: string) => ({ neutral: "기본", smile: "미소", sad: "슬픔", surprised: "놀람" })[expression] ?? expression;
/** 장면 이름·선택지 문구·엔딩 제목의 입력 상한. 파서는 더 긴 값도 허용하지만 화면에 담기는 길이는 이 정도다. */
export const LABEL_MAX = 200;
interface Props {
  script: VnScript; scene: Scene; lineIndex: number;
  patchScene: (scene: Scene, group?: string) => boolean | void;
  patchLine: (line: Line) => boolean | void;
  onChange: (script: VnScript) => boolean | void;
  /** Ctrl/Cmd+Enter: 이 대사 뒤에 새 줄을 만들고 그 줄로 포커스를 옮긴다. */
  onAddLine?: () => void;
  /** 여러 줄을 붙여넣었을 때. replaceCurrent 면 첫 줄이 현재 대사를 채운다. */
  onInsertLines?: (lines: readonly Line[], replaceCurrent: boolean) => void;
  /** 씬 ID 변경. 실패 사유를 돌려주면 필드 아래에 표시한다. */
  onRenameScene?: (id: string) => string | null;
  textRef?: RefObject<HTMLTextAreaElement | null>;
  /** 스토어 설치가 끝난 뒤 프로젝트가 바뀌었는지 가려 내는 시대 값. */
  projectEpoch?: number;
}

/** 장면 연결 select 의 옵션 목록. id·제목 서명이 같으면 다시 만들지 않는다 — 장편에서 키 입력마다 256개 option 을 만들 이유가 없다. */
const SceneOptions = memo(function SceneOptions({ scenes }: { scenes: VnScript["scenes"] }) {
  return <>{scenes.map(row => <option key={row.id} value={row.id}>{sceneTitle(row)}</option>)}</>;
});

function SceneIdField({ sceneId, onRename }: { sceneId: string; onRename: (id: string) => string | null }) {
  const [draft, setDraft] = useState(sceneId), [error, setError] = useState("");
  useEffect(() => { setDraft(sceneId); setError(""); }, [sceneId]);
  function commit() { const next = draft.trim(); if (!next || next === sceneId) { setDraft(sceneId); setError(""); return; } const issue = onRename(next); if (issue) setError(issue); }
  return <label className="studio-field">씬 ID<input data-testid="studio-scene-id" aria-label="씬 ID" value={draft} maxLength={64} spellCheck={false} onChange={event => { setDraft(event.target.value); setError(""); }} onBlur={commit} onKeyDown={event => { if (event.key === "Enter") { event.preventDefault(); commit(); } if (event.key === "Escape") { setDraft(sceneId); setError(""); } }} />{error ? <small role="alert" className="field-error">{error}</small> : <small className="field-help">바꾸면 시작 위치·다음 씬·선택지 연결이 함께 갱신됩니다.</small>}</label>;
}

export function Inspector({ script, scene, lineIndex, patchScene, patchLine, onChange, onAddLine, onInsertLines, onRenameScene, textRef, projectEpoch }: Props) {
  const line = scene.lines[lineIndex]!;
  const optionKey = script.scenes.map(row => `${row.id}\u0001${row.chapter ?? ""}`).join("\n");
  // eslint-disable-next-line react-hooks/exhaustive-deps -- 서명이 같으면 옵션 목록이 같다.
  const optionScenes = useMemo(() => script.scenes, [optionKey]);
  const remaining = LIMITS.text - line.text.length;
  function patchActor(slot:string,patch:Partial<SpriteDirection>){const current=spritesAt(scene,Math.max(0,lineIndex-1)).find(sprite=>sprite.slot===slot);const old=line.sprites?.find(sprite=>sprite.slot===slot);patchLine({...line,sprites:[...(line.sprites??[]).filter(sprite=>sprite.slot!==slot),{slot,character:old?.character??current?.character??null,...old,...patch}]});}
  function exit(value: string) {
    const { choices: _choices, next: _next, ending: _ending, ...rest } = scene;
    patchScene({ ...rest, ...(value === "ending" ? { ending: scene.chapter || "이야기의 끝" } : { next: value }) });
  }
  return <div className="inspector-content">
    <div className="section-kicker">DIALOGUE <span>{String(lineIndex + 1).padStart(2, "0")}</span></div>
    <label className="studio-field">대사<textarea ref={textRef} data-testid="studio-line-text" value={line.text} rows={5} maxLength={LIMITS.text} onChange={event => patchLine({ ...line, text: event.target.value })} onKeyDown={event => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter" && onAddLine) { event.preventDefault(); onAddLine(); } }} onPaste={event => {
      if (!onInsertLines) return;
      const lines = splitPastedText(event.clipboardData.getData("text/plain"), script.characters);
      if (lines.length < 2) return;
      event.preventDefault();
      onInsertLines(lines, line.text.trim() === "");
    }} />{remaining <= 2000 && <small className={`capacity-hint ${remaining <= 0 ? "is-full" : ""}`} data-testid="studio-line-capacity">{remaining.toLocaleString()}자 남음 · 최대 {LIMITS.text.toLocaleString()}자</small>}<small className="field-help">Ctrl+Enter 로 다음 줄 · 여러 줄을 붙여넣으면 줄마다 나눕니다</small></label>
    <div className="field-pair"><label className="studio-field">화자<select aria-label="화자" value={line.speaker ?? ""} onChange={event => { const speaker = (event.target.value || null) as Line["speaker"]; const actor = speaker ? script.characters.find(c => c.id === speaker) : undefined; const text = actor ? stripSpeakerPrefix(line.text, actor) : line.text; patchLine({ ...line, speaker, text }); }}><option value="">내레이션</option>{!script.characters.some(actor=>actor.id==="me") && script.scenes.some(row=>row.lines.some(line=>line.speaker==="me")) && <option value="me">기존 주인공 (me)</option>}{script.characters.map(character => <option key={character.id} value={character.id}>{character.name}</option>)}</select></label><label className="studio-field">표정<select aria-label="표정" value={line.expression ?? ""} onChange={event => { const { expression: _expression, ...rest } = line; patchLine(event.target.value ? { ...rest, expression: event.target.value as Expression } : rest); }}><option value="">유지</option>{characterExpressions(script.characters.find(actor=>actor.id===line.speaker)).map(value => <option key={value} value={value}>{expressionLabel(value)}</option>)}</select></label></div>
    <AudioLibrary script={script} onChange={onChange} projectEpoch={projectEpoch}/><label className="studio-field">보이스<select aria-label="대사 보이스" value={line.voice??""} onChange={event=>{const {voice:old,...rest}=line;patchLine(event.target.value?{...rest,voice:event.target.value}:rest);}}><option value="">없음</option><AudioOptions script={script} kind="voice" current={line.voice}/></select></label>
    <label className="studio-field">효과음<select aria-label="대사 효과음" value={line.sfx ?? ""} onChange={event => { const { sfx: _sfx, ...rest } = line; patchLine(event.target.value ? { ...rest, sfx: event.target.value } : rest); }}><option value="">없음</option><AudioOptions script={script} kind="sfx" current={line.sfx}/>{Object.entries(SFX).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    <label className="check-field"><input type="checkbox" checked={line.shake ?? false} onChange={event => patchLine({ ...line, shake: event.target.checked })} />화면 흔들림</label>
    <label className="studio-field" style={{ marginTop: 18 }}>이 대사에서 배경 전환<select aria-label="이 대사에서 배경 전환" data-testid="studio-line-background" value={line.backgroundUrl ?? ""} onChange={event => { const { backgroundUrl: _background, ...rest } = line; patchLine(event.target.value ? { ...rest, backgroundUrl: event.target.value } : rest); }}><option value="">이전 배경 유지</option>{line.backgroundUrl && !script.assets?.some(asset => asset.kind === "background" && asset.url === line.backgroundUrl) && <option value={line.backgroundUrl}>현재 지정된 배경</option>}{script.assets?.filter(asset => asset.kind === "background").map(asset => <option value={asset.url} key={asset.id}>{asset.name}</option>)}</select></label>
    <label className="studio-field" style={{ marginTop: 18 }}>이 대사에서 이미지 전환<select aria-label="대사 CG 연출" value={line.cgUrl === null ? "clear" : line.cgUrl ?? "inherit"} onChange={event => { const { cgUrl: _cue, ...rest } = line; patchLine(event.target.value === "inherit" ? rest : { ...rest, cgUrl: event.target.value === "clear" ? null : event.target.value }); }}><option value="inherit">이전 이미지 유지</option><option value="clear">장면 배경으로 돌아오기</option>{script.assets?.filter(asset => asset.kind === "cg").map(asset => <option value={asset.url} key={asset.id}>CG · {asset.name}</option>)}</select></label>
    <label className="check-field"><input type="checkbox" aria-label="이 대사에서 CG 잠시 숨기기" checked={line.cgHide ?? false} onChange={event => { const { cgHide: _hide, ...rest } = line; patchLine(event.target.checked ? { ...rest, cgHide: true } : rest); }} />이 대사에서 CG 잠시 숨기기</label>
    <details className="line-direction"><summary>이 대사의 배우·카메라·음악</summary>
      <label className="studio-field">구도 전환<select aria-label="대사 카메라" value={line.framing??""} onChange={event=>{const{framing:_framing,...rest}=line;patchLine(event.target.value?{...rest,framing:event.target.value as NonNullable<Line["framing"]>}:rest);}}><option value="">이전 구도 유지</option><option value="wide">와이드</option><option value="close">클로즈업</option><option value="cinematic">시네마틱</option></select></label>
      <label className="studio-field">음악 전환<select aria-label="대사 배경음악" value={line.bgm===null?"stop":line.bgm??""} onChange={event=>{const{bgm:_bgm,...rest}=line;patchLine(event.target.value?{...rest,bgm:event.target.value==="stop"?null:event.target.value}:rest);}}><option value="">이전 음악 유지</option><option value="stop">음악 멈추기</option><AudioOptions script={script} kind="bgm" current={line.bgm??undefined}/>{Object.entries(BGM).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
      {(["left","center","right"] as const).map(slot=>{const cue=line.sprites?.find(sprite=>sprite.slot===slot);const actor=cue?.character??spritesAt(scene,lineIndex).find(sprite=>sprite.slot===slot)?.character;return <div className="actor-cue" key={slot}><label className="studio-field">{slot==="left"?"왼쪽":slot==="right"?"오른쪽":"중앙"} 배우<select aria-label={`${slot} 대사 배우`} value={cue?cue.character??"leave":""} onChange={event=>{if(!event.target.value){const{sprites,...rest}=line;const next=(sprites??[]).filter(sprite=>sprite.slot!==slot);patchLine(next.length?{...rest,sprites:next}:rest);}else patchActor(slot,{character:event.target.value==="leave"?null:event.target.value,poseUrl:null});}}><option value="">이전 배치 유지</option><option value="leave">퇴장</option>{script.characters.map(character=><option key={character.id} value={character.id}>{character.name}</option>)}</select></label><label className="studio-field">포즈<select aria-label={`${slot} 대사 포즈`} disabled={!actor} value={cue?.poseUrl===null?"clear":cue?.poseUrl??""} onChange={event=>{if(!event.target.value){if(!cue)return;const{poseUrl:_pose,...rest}=cue;patchLine({...line,sprites:line.sprites!.map(row=>row.slot===slot?rest:row)});}else patchActor(slot,{poseUrl:event.target.value==="clear"?null:event.target.value});}}><option value="">이전 포즈 유지</option><option value="clear">기본 표정 원화로 복귀</option>{script.assets?.filter(asset=>asset.kind==="character"&&asset.characterId===actor).map(asset=><option key={asset.id} value={asset.url}>{asset.name}</option>)}</select></label>{(()=>{const outfits=script.characters.find(character=>character.id===actor)?.outfits??[];return outfits.length?<label className="studio-field">의상<select aria-label={`${slot} 대사 의상`} value={cue?.outfit===null?"clear":cue?.outfit??""} onChange={event=>{if(!event.target.value){if(!cue)return;const{outfit:_outfit,...rest}=cue;patchLine({...line,sprites:line.sprites!.map(row=>row.slot===slot?rest:row)});}else patchActor(slot,{outfit:event.target.value==="clear"?null:event.target.value});}}><option value="">이전 의상 유지</option><option value="clear">기본 복장으로 복귀</option>{outfits.map(outfit=><option key={outfit} value={outfit}>{outfit}</option>)}</select></label>:null;})()}</div>;})}
    </details>
    <StateEditor script={script} onChange={onChange}/><ConditionEditor label="대사 표시 조건" flags={script.flags??{}} value={line.when} onChange={when=>{const {when:old,...rest}=line;patchLine(when?{...rest,when}:rest);}}/>
    <div className="section-kicker">SCENE <Icon name="scenes" size={14} /></div>
    <label className="studio-field">씬 이름<input aria-label="씬 이름" value={scene.chapter ?? ""} maxLength={LABEL_MAX} onChange={event => patchScene({ ...scene, chapter: event.target.value }, `chapter-${scene.id}`)} /></label>
    {onRenameScene && <SceneIdField sceneId={scene.id} onRename={onRenameScene} />}
    <label className="studio-field">배경<select aria-label="장면 배경" value={scene.backgroundUrl ?? scene.background} onChange={event => { const { backgroundUrl: _url, cgUrl: _cg, ...rest } = scene; patchScene(event.target.value.startsWith("/") ? { ...rest, backgroundUrl: event.target.value } : { ...rest, background: event.target.value }); }}>{scene.backgroundUrl && !script.assets?.some(asset => asset.url === scene.backgroundUrl) && <option value={scene.backgroundUrl}>프로젝트 배경</option>}{script.assets?.filter(asset => asset.kind === "background").map(asset => <option key={asset.id} value={asset.url}>{asset.name}</option>)}<optgroup label="기본 배경">{Object.entries(BACKGROUNDS).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</optgroup></select></label>
    <label className="studio-field">배경음악<select aria-label="장면 배경음악" value={scene.bgm ?? ""} onChange={event => { const { bgm: _bgm, ...rest } = scene; patchScene(event.target.value ? { ...rest, bgm: event.target.value } : rest); }}><option value="">없음</option><AudioOptions script={script} kind="bgm" current={scene.bgm}/>{Object.entries(BGM).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    <label className="studio-field">장면 전환<select value={scene.transition ?? "none"} onChange={event => patchScene({ ...scene, transition: event.target.value as Scene["transition"] & string })}>{[["none", "없음"], ["fade", "페이드"], ["dissolve", "디졸브"], ["flash", "플래시"], ["fadeToBlack", "암전"]].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>
    <div className="section-kicker">ART & CAMERA <Icon name="image" size={14} /></div>
    <label className="studio-field">장면 이벤트 CG<select aria-label="장면 이벤트 CG" value={scene.cg ?? scene.cgUrl ?? ""} onChange={event => { const { cg: _cg, cgUrl: _cgUrl, ...rest } = scene; const asset = script.assets?.find(row => row.id === event.target.value); patchScene(asset ? { ...rest, cg: asset.id } : event.target.value ? { ...rest, cgUrl: event.target.value } : rest); }}><option value="">없음</option>{scene.cgUrl && !script.assets?.some(asset => asset.url === scene.cgUrl) && <option value={scene.cgUrl}>현재 지정된 CG</option>}{script.assets?.filter(asset => asset.kind === "cg").map(asset => <option value={asset.id} key={asset.id}>CG · {asset.name}</option>)}</select></label>
    {scene.cgUrl && <div className="inspector-cg"><img src={scene.cgUrl} alt="현재 장면의 이벤트 CG" /><div><span>이벤트 CG 적용 중</span><button type="button" className="text-button" onClick={() => { const { cgUrl: _cg, ...rest } = scene; patchScene(rest); }}>CG 해제</button></div></div>}
    <label className="studio-field">카메라 프레이밍<select aria-label="카메라 프레이밍" value={scene.framing ?? "wide"} onChange={event => patchScene({ ...scene, framing: event.target.value as NonNullable<Scene["framing"]> })}><option value="wide">와이드 · 전체 장면</option><option value="close">클로즈업 · 감정 강조</option><option value="cinematic">시네마틱 · 레터박스</option></select></label>
    <label className="check-field"><input type="checkbox" checked={scene.hideSprites ?? false} onChange={event => patchScene({ ...scene, hideSprites: event.target.checked })} />배우 없이 배경만 보여주기</label>
    <p className="field-help" style={{ marginTop: 10 }}>이벤트 CG가 있으면 배우 이미지 대신 CG를 표시합니다.</p>
    <label className="studio-field">장면 아트 브리프<textarea aria-label="장면 연출 메모" value={scene.artBrief ?? ""} rows={3} maxLength={4000} placeholder="시간대, 빛, 소품, 감정의 시각적 모티프…" onChange={event => patchScene({ ...scene, artBrief: event.target.value }, `art-${scene.id}`)} /></label>
    <div className="section-kicker">CAST <Icon name="users" size={14} /></div>
    {(["left", "center", "right"] as const).map(slot => <label className="studio-field" key={slot}>{slot === "left" ? "왼쪽" : slot === "center" ? "중앙" : "오른쪽"}<select aria-label={`${slot} 배우`} value={scene.sprites?.find(sprite => sprite.slot === slot)?.character ?? ""} onChange={event => { const sprites = (scene.sprites ?? []).filter(sprite => sprite.slot !== slot); const character = event.target.value as SpriteDirection["character"]; patchScene({ ...scene, sprites: character ? [...sprites, { slot, character, expression: "neutral" }] : sprites }); }}><option value="">비우기</option>{script.characters.map(character => <option key={character.id} value={character.id}>{speakerName(script, character.id)}</option>)}</select></label>)}
    <div className="section-kicker">STORY FLOW <Icon name="graph" size={14} /></div>
    {scene.choices?.length ? <div className="choice-fields">{scene.choices.map((choice, index) => <div className="choice-edit" key={index}><div className="choice-edit-heading"><span>선택지 {index + 1}</span><button type="button" className="icon-button" aria-label={`선택지 ${index + 1} 삭제`} onClick={() => { const choices = scene.choices!.filter((_, i) => i !== index); if (choices.length) patchScene({ ...scene, choices }); else exit("ending"); }}><Icon name="close" size={13} /></button></div><input aria-label={`선택지 ${index + 1} 문구`} value={choice.text} maxLength={LABEL_MAX} onChange={event => patchScene({ ...scene, choices: scene.choices!.map((row, i) => i === index ? { ...row, text: event.target.value } : row) }, `choice-${scene.id}-${index}`)} /><select aria-label={`선택지 ${index + 1} 연결`} value={choice.next} onChange={event => patchScene({ ...scene, choices: scene.choices!.map((row, i) => i === index ? { ...row, next: event.target.value } : row) })}><SceneOptions scenes={optionScenes} /></select><ChoiceStateEditor choice={choice} index={index} flags={script.flags??{}} onChange={next=>patchScene({...scene,choices:scene.choices!.map((row,i)=>i===index?next:row)})}/></div>)}</div> : <label className="studio-field">이 씬이 끝나면<select aria-label="씬 종료 방식" value={scene.ending ? "ending" : scene.next ?? ""} onChange={event => exit(event.target.value)}><option value="" disabled>연결할 씬 선택</option><option value="ending">엔딩 표시</option><SceneOptions scenes={optionScenes} /></select></label>}
    {scene.ending && !scene.choices?.length && <label className="studio-field">엔딩 제목<input value={scene.ending} maxLength={LABEL_MAX} onChange={event => patchScene({ ...scene, ending: event.target.value }, `ending-${scene.id}`)} /></label>}
    <button className="studio-button full-width" type="button" disabled={(scene.choices?.length ?? 0) >= LIMITS.choices} onClick={() => { const { ending: _ending, next: _next, ...rest } = scene; const target = scene.next ?? script.scenes.find(row => row.id !== scene.id)?.id ?? scene.id; patchScene({ ...rest, choices: [...(scene.choices ?? []), { text: "새로운 선택", next: target }] }); }}><Icon name="plus" />선택지 추가</button>
  </div>;
}
