import { auditScript, characterExpressions, characterImage, type VnScript } from "@vnmaker/content";
import { nativeExportBlocks, nativeTransition } from "./nativeParity.js";
import { projectPublicScript } from "./releaseSnapshot.js";

export { RENPY_DIRECTION_RUNTIME } from "./renpyDirection.js";

/** Ren'Py text interpolation and markup are escaped separately from Python quoting. */
export const renpyText = (value: string) => JSON.stringify(value.replace(/\[/g, "[[").replace(/\{/g, "{{"));
const pythonJson = (value: unknown) => `json.loads(${JSON.stringify(JSON.stringify(value))})`;
const label = (id: string) => `vn_scene_${Array.from(new TextEncoder().encode(id)).map(byte => byte.toString(16).padStart(2, "0")).join("")}`;

/** Native statements preserve Ren'Py's save/rollback boundaries for every dialogue and choice. */
export function generateRenpyScript(source: VnScript): string {
  const script = projectPublicScript(source);
  const errors = auditScript(script).filter(issue => issue.severity === "error");
  if (errors.length) throw new Error(errors.map(issue => issue.message).join("\n"));
  const blocks = nativeExportBlocks(script);
  if (blocks.length) throw new Error(blocks.map(block => block.message).join("\n"));
  if (script.scenes.some(scene => scene.choices?.length && scene.choices.every(choice => choice.disable))) {
    throw new Error("모든 선택지가 잠긴 장면은 내보낼 수 없습니다.");
  }
  const data = {
    ...script,
    characters: script.characters.map(actor => ({
      ...actor,
      expressionImages: Object.fromEntries(characterExpressions(actor).flatMap(expression => {
        const url = characterImage(actor, expression);
        return url ? [[expression, url]] : [];
      })),
    })),
  };
  const out = [`# Generated by VN Maker. Native exporter preview; verify the game before release.\ninit python:\n    import json\n    vn_project = ${pythonJson(data)}\n\ndefault vn_flags = ${pythonJson(script.flags ?? {})}\ndefault vn_affection = 0\ndefault vn_slots = {}\ndefault vn_background = None\ndefault vn_cg = None\ndefault vn_framing = "wide"\ndefault vn_hide_actors = False\n`];
  script.characters.forEach((actor, index) => out.push(`define vn_actor_${index} = Character(${renpyText(actor.name)}, color=${JSON.stringify(actor.color)})`));
  if (!script.characters.some(actor => actor.id === "me")) out.push(`define vn_legacy_me = Character("정우진", color="#b7c6d4")`);
  out.push(`\nlabel start:\n    jump ${label(script.start)}\n`);
  [...script.scenes].sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0).forEach(scene => {
    const sceneIndex = JSON.stringify(scene.id);
    out.push(`label ${label(scene.id)}:\n    $ vn_enter(${sceneIndex})`);
    if (scene.transition) {
      const clause = nativeTransition(scene.transition);
      if (clause) out.push(`    with ${clause}`);
    }
    scene.lines.forEach((line, lineIndex) => {
      const conditional = !!line.when;
      if (conditional) out.push(`    if vn_allowed(${sceneIndex}, ${lineIndex}):`);
      const indent = conditional ? "        " : "    ";
      out.push(`${indent}$ vn_cue(${sceneIndex}, ${lineIndex})`);
      if (line.voice) out.push(`${indent}voice ${JSON.stringify(line.voice.replace(/^\//, ""))}`);
      if (line.shake) out.push(`${indent}with vpunch`);
      const actor = script.characters.findIndex(row => row.id === line.speaker);
      const who = line.speaker === null ? "" : actor >= 0 ? `vn_actor_${actor} ` : "vn_legacy_me ";
      out.push(`${indent}${who}${renpyText(line.text)}`);
    });
    if (scene.choices?.length) {
      out.push("    menu:");
      scene.choices.forEach((choice, choiceIndex) => {
        out.push(`        ${renpyText(choice.text)}${choice.disable ? " if False" : choice.add ? ` if vn_choice_allowed(vn_scene(${sceneIndex})["choices"][${choiceIndex}])` : choice.when ? ` if vn_condition(vn_scene(${sceneIndex})["choices"][${choiceIndex}].get("when", {}))` : ""}:`);
        if (choice.add) out.push(`            $ vn_flags = vn_apply_flags(vn_scene(${sceneIndex})["choices"][${choiceIndex}])`);
        else if (choice.set) out.push(`            $ vn_flags = dict(vn_flags, **${pythonJson(choice.set)})`);
        if (choice.affection) out.push(`            $ vn_affection += ${choice.affection}`);
        out.push(`            jump ${label(choice.next)}`);
      });
    } else if (scene.ending) {
      out.push("    window hide", `    call screen vn_ending(${renpyText(scene.ending)})`, "    return");
    } else if (scene.next) out.push(`    jump ${label(scene.next)}`);
    else out.push("    return");
    out.push("");
  });
  return out.join("\n");
}
