import { useEffect, useRef, useState } from "react";
import type { Scene, VnScript } from "@vnmaker/content";
import { duplicateScene, moveScene, removeScene, sceneRemovalIssue } from "./sceneOperations.js";
import { newSceneId, sceneTitle } from "./project.js";
import { Icon } from "./Icon.js";

export function SceneTools({script,scene,onChange,onSelect}:{script:VnScript;scene:Scene;onChange:(script:VnScript)=>void;onSelect:(id:string)=>void}){
  const [open,setOpen]=useState(false);const[replacement,setReplacement]=useState("");const[error,setError]=useState("");const dialog=useRef<HTMLDialogElement>(null);
  const index=script.scenes.findIndex(row=>row.id===scene.id);
  const inbound=script.scenes.filter(row=>row.id!==scene.id&&(row.next===scene.id||row.choices?.some(choice=>choice.next===scene.id))).length;
  const replacementIssue=replacement ? sceneRemovalIssue(script,scene.id,replacement) : null;
  useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
  return <><div className="scene-tools" aria-label="장면 구성 편집"><button type="button" data-testid="scene-duplicate" onClick={()=>{const id=newSceneId();onChange(duplicateScene(script,scene.id,id));onSelect(id);}}><Icon name="scenes" size={13}/>복제</button><button type="button" aria-label="장면 목록에서 위로 이동" disabled={index===0} onClick={()=>onChange(moveScene(script,scene.id,index-1))}>↑</button><button type="button" aria-label="장면 목록에서 아래로 이동" disabled={index===script.scenes.length-1} onClick={()=>onChange(moveScene(script,scene.id,index+1))}>↓</button><small>목록 순서 · 연결 유지</small><button type="button" data-testid="scene-delete" disabled={script.scenes.length<2} onClick={()=>{setReplacement(scene.next!==scene.id?scene.next??"":"");setError("");setOpen(true);}}><Icon name="trash" size={13}/>삭제</button></div>
  <dialog ref={dialog} className="studio-modal scene-delete-dialog" aria-label="장면 삭제" onCancel={()=>setOpen(false)}><header><h2>장면 삭제</h2><button aria-label="장면 삭제 닫기" onClick={()=>setOpen(false)}>×</button></header><p><strong>{sceneTitle(scene)}</strong>의 원고를 삭제하고 연결된 {inbound}개 장면의 다음 경로를 정리합니다.{script.start===scene.id?" 작품의 시작 위치도 아래 장면으로 바뀝니다.":""}</p><label>삭제 후 연결할 장면<select aria-label="삭제 후 연결할 장면" value={replacement} onChange={event=>{setReplacement(event.target.value);setError("");}}><option value="">장면 선택</option>{script.scenes.filter(row=>row.id!==scene.id).map(row=>{const issue=sceneRemovalIssue(script,scene.id,row.id);return <option key={row.id} value={row.id} disabled={!!issue} title={issue??undefined}>{sceneTitle(row)}{issue?" — 자기 연결을 만들 수 없음":""}</option>;})}</select></label><p className="field-help">선택한 장면이 삭제할 장면으로 연결되어 있다면, 삭제 장면의 다음 연결·선택지·엔딩을 이어받습니다. 이미지 파일은 보관하며 실행 취소로 복원할 수 있습니다.</p>{(error||replacementIssue)&&<p role="alert">{error||replacementIssue}</p>}<footer><button className="studio-button" onClick={()=>setOpen(false)}>취소</button><button className="studio-button danger" data-testid="scene-delete-confirm" disabled={!replacement||!!replacementIssue} onClick={()=>{try{onChange(removeScene(script,scene.id,replacement));onSelect(replacement);setOpen(false);}catch(error){setError(String(error));}}}>장면 삭제</button></footer></dialog></>;
}
